api_platform:
    title: Hello API Platform
    description: "erferferferferferf"
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json:     ['application/json']
        multipart: ['multipart/form-data']
        octet_stream: ['application/octet-stream']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: true
    keep_legacy_inflector: false
    exception_to_status:
        Doctrine\ORM\EntityNotFoundException: 404

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'