gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000 # 30 days
  token_parameter_name: refreshToken
#  cookie:
#    enabled: true
#    same_site: lax               # default value
#    path: /                      # default value
#    domain: null                 # default value
#    http_only: true              # default value
#    secure: true                 # default value
#    remove_token_from_body: true # default value