#lexik_jwt_authentication:
#    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
#    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
#    pass_phrase: '%env(JWT_PASSPHRASE)%'
#    user_identity_field: sub
#    encoder:
#        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
#        service: lexik_jwt_authentication.encoder.lcobucci
#
#        # encryption algorithm used by the encoder service
#        signature_algorithm: RS256
parameters:
    app.jwt_public_key: '%kernel.project_dir%/secret/jwt/public.pem'

lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/secret/jwt/private.pem'
    public_key: '%app.jwt_public_key%'
    pass_phrase: 'passphrase'
    user_identity_field: sub
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service: lexik_jwt_authentication.encoder.lcobucci

        # encryption algorithm used by the encoder service
        signature_algorithm: RS256