vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        certificate_upload:
            uri_prefix: /uploads/certificates
            upload_destination: '%kernel.project_dir%/public/uploads/certificates'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true