<?php

namespace App\Enum;

enum UserRoleEnum: string
{
    const ROLE_USER = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';
    const ROLE_MUNICIPALITY_HEAD = 'ROLE_MUNICIPALITY_HEAD';
    const ROLE_MUNICIPALITY_MANAGER = 'ROLE_MUNICIPALITY_MANAGER';
    const ROLE_OPERATOR = 'ROLE_OPERATOR';
    case ROLE_USER_CASE = self::ROLE_USER;
    case ROLE_SUPER_ADMIN_CASE = self::ROLE_SUPER_ADMIN;
    case ROLE_ADMIN = 'ROLE_ADMIN';
    case ROLE_MUNICIPALITY_HEAD_CASE = self::ROLE_MUNICIPALITY_HEAD;
    case ROLE_MUNICIPALITY_MANAGER_CASE = self::ROLE_MUNICIPALITY_MANAGER;
    case ROLE_OPERATOR_CASE = self::ROLE_OPERATOR;
    case ROLE_ENGINEER = 'ROLE_ENGINEER';
    case ROLE_ORGANIZATION_JOIN_TASK = 'ROLE_ORGANIZATION_JOIN_TASK';
    case ROLE_ORGANIZATION_JOIN_FLOW = 'ROLE_ORGANIZATION_JOIN_FLOW';
    case ROLE_ORGANIZATION_JOIN_INVITE = 'ROLE_ORGANIZATION_JOIN_INVITE';
    case ROLE_ORGANIZATION = 'ROLE_ORGANIZATION';
    case ROLE_ORGANIZATION_ROLE = 'ROLE_ORGANIZATION_ROLE';
    case ROLE_ORGANIZATION_ROLE_DELETE = 'ROLE_ORGANIZATION_ROLE_DELETE';
    case ROLE_WITHOUT_ORGANIZATION = 'ROLE_WITHOUT_ORGANIZATION';
    case ROLE_FORMIO = 'ROLE_FORMIO';
    case ROLE_FORMIO_CREATE = 'ROLE_FORMIO_CREATE';
    case ROLE_FORMIO_VIEW = 'ROLE_FORMIO_VIEW';
    case ROLE_FORMIO_EDIT = 'ROLE_FORMIO_EDIT';
    case ROLE_FORMIO_DELETE = 'ROLE_FORMIO_DELETE';
    case ROLE_APPLICATION = 'ROLE_APPLICATION';
    case ROLE_APPLICATION_TASK = 'ROLE_APPLICATION_TASK';
    case ROLE_APPLICATION_TASK_CONFIRM = 'ROLE_APPLICATION_TASK_CONFIRM';
    case ROLE_APPLICATION_SUBMISSION = 'ROLE_APPLICATION_SUBMISSION';
    case ROLE_CAMUNDA_STRATEGY = 'ROLE_CAMUNDA_STRATEGY';
    case ROLE_APPLICATION_OWNER_FOR_ALL = 'ROLE_APPLICATION_OWNER_FOR_ALL';
    case ROLE_APPLICATION_TASK_OWNER_FOR_ALL = 'ROLE_APPLICATION_TASK_OWNER_FOR_ALL';
    case ROLE_CAMUNDA_TASK = 'ROLE_CAMUNDA_TASK';
    case ROLE_NATIVE_STRATEGY = 'ROLE_NATIVE_STRATEGY';
    case ROLE_USER_CRUD = 'ROLE_USER_CRUD';
    case ROLE_MANAGER = 'ROLE_MANAGER';

    /**
     * @return UserRoleEnum[]
     */
    public static function getAdminRoles(): array
    {
        return [
            self::ROLE_OPERATOR_CASE,
            self::ROLE_ENGINEER,
        ];
    }

    /**
     * @return UserRoleEnum[]
     */
    public static function getOrganizationRoles(): array
    {
        return [
            self::ROLE_MUNICIPALITY_MANAGER_CASE,
            self::ROLE_MUNICIPALITY_HEAD_CASE,
        ];
    }
}
