<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241206121523 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA application_flow');
        $this->addSql('CREATE SEQUENCE application_process_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE application_task_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE application_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE camunda_strategy_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE application_flow.camunda_task_filter_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE certificate_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE email_template_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE file_upload_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE form_io_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE form_io_process_resource_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE form_process_submission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE form_process_submission_variable_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE form_submission_edit_locker_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE form_task_submission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE guide_book_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE guide_book_translation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE installer_email_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE installer_quota_submission_id_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE native_strategy_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE oauth_state_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_join_flow_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_join_flow_data_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_join_invite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_join_task_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE organization_user_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refresh_tokens_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE site_redirect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE application_process (id INT NOT NULL, user_id INT DEFAULT NULL, type_id INT DEFAULT NULL, process_instance_id VARCHAR(255) NOT NULL, title VARCHAR(255) DEFAULT NULL, process_created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6DA31DA5A76ED395 ON application_process (user_id)');
        $this->addSql('CREATE INDEX IDX_6DA31DA5C54C8C93 ON application_process (type_id)');
        $this->addSql('CREATE TABLE application_task (id INT NOT NULL, form_id INT DEFAULT NULL, type_id INT DEFAULT NULL, parent_task_id INT DEFAULT NULL, process_instance_id VARCHAR(255) NOT NULL, task_id VARCHAR(255) NOT NULL, completed BOOLEAN NOT NULL, user_identifier VARCHAR(255) DEFAULT NULL, role VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A592B3AD5FF69B7D ON application_task (form_id)');
        $this->addSql('CREATE INDEX IDX_A592B3ADC54C8C93 ON application_task (type_id)');
        $this->addSql('CREATE INDEX IDX_A592B3ADFFFE75C0 ON application_task (parent_task_id)');
        $this->addSql('CREATE TABLE application_type (id INT NOT NULL, alias VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, role VARCHAR(255) NOT NULL, strategy_type VARCHAR(255) NOT NULL, allow_start_process BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B323FA1E16C6B94 ON application_type (alias)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B323FA12B36786B ON application_type (title)');
        $this->addSql('CREATE TABLE camunda_strategy (id INT NOT NULL, default_form_id INT DEFAULT NULL, type_id INT DEFAULT NULL, table_form_id INT DEFAULT NULL, camunda_alias VARCHAR(255) DEFAULT NULL, tenant_id VARCHAR(255) DEFAULT NULL, all_tasks_one_user BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_58CFFD0FAD73CA38 ON camunda_strategy (default_form_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58CFFD0FC54C8C93 ON camunda_strategy (type_id)');
        $this->addSql('CREATE INDEX IDX_58CFFD0F5DC5DA72 ON camunda_strategy (table_form_id)');
        $this->addSql('CREATE TABLE application_flow.camunda_task_filter (id INT NOT NULL, camunda_strategy_id INT DEFAULT NULL, property VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A3D6132CC7D4C284 ON application_flow.camunda_task_filter (camunda_strategy_id)');
        $this->addSql('CREATE TABLE certificate (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, organization VARCHAR(255) DEFAULT NULL, issue_date DATE DEFAULT NULL, expiry_date DATE DEFAULT NULL, is_indefinite BOOLEAN NOT NULL, course_url VARCHAR(255) DEFAULT NULL, course_name VARCHAR(255) DEFAULT NULL, course_author VARCHAR(255) DEFAULT NULL, certificate_file VARCHAR(255) DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, created_at DATE DEFAULT NULL, updated_at DATE DEFAULT NULL, status VARCHAR(255) DEFAULT NULL, course_source VARCHAR(255) DEFAULT NULL, user_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE email_template (id INT NOT NULL, subject VARCHAR(255) NOT NULL, message TEXT NOT NULL, use_in VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE file_upload (id INT NOT NULL, identifier VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, upload_by_identifier VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE form_io (id INT NOT NULL, started_process_type_id INT DEFAULT NULL, form_key VARCHAR(255) NOT NULL, form_id VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, application_public_form BOOLEAN DEFAULT NULL, installer_proposal_form BOOLEAN DEFAULT NULL, manager_proposal_form BOOLEAN DEFAULT NULL, filter_by_application_number_path VARCHAR(255) DEFAULT NULL, filter_by_status_path VARCHAR(255) DEFAULT NULL, confirmed_status_value VARCHAR(255) DEFAULT NULL, draft_status_value VARCHAR(255) DEFAULT NULL, email_property_path VARCHAR(255) DEFAULT NULL, application_number_property_path VARCHAR(255) DEFAULT NULL, first_name_property_path VARCHAR(255) DEFAULT NULL, last_name_property_path VARCHAR(255) DEFAULT NULL, application_resource_path VARCHAR(255) DEFAULT NULL, address_property_path VARCHAR(255) DEFAULT NULL, zip_code_property_path VARCHAR(255) DEFAULT NULL, status_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82442F5CFAF3820 ON form_io (form_key)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82442F55FF69B7D ON form_io (form_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C82442F52B36786B ON form_io (title)');
        $this->addSql('CREATE INDEX IDX_C82442F5C24EAF86 ON form_io (started_process_type_id)');
        $this->addSql('CREATE TABLE form_io_process_resource (id INT NOT NULL, parent_form_id INT DEFAULT NULL, resource_id INT DEFAULT NULL, path VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_93C3B8752DBEEF3B ON form_io_process_resource (parent_form_id)');
        $this->addSql('CREATE INDEX IDX_93C3B87589329D25 ON form_io_process_resource (resource_id)');
        $this->addSql('CREATE TABLE form_process_submission (id INT NOT NULL, form_id INT DEFAULT NULL, process_instance_id VARCHAR(255) NOT NULL, submission_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5CD290805FF69B7D ON form_process_submission (form_id)');
        $this->addSql('CREATE TABLE form_process_submission_variable (id INT NOT NULL, key VARCHAR(255) NOT NULL, submission_property VARCHAR(255) NOT NULL, process_instance_id VARCHAR(255) NOT NULL, submission_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE form_submission_edit_locker (id INT NOT NULL, submission_id VARCHAR(255) NOT NULL, locked BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE form_task_submission (id INT NOT NULL, form_id INT DEFAULT NULL, process_id VARCHAR(255) DEFAULT NULL, task_id VARCHAR(255) NOT NULL, submission_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_77704C855FF69B7D ON form_task_submission (form_id)');
        $this->addSql('CREATE TABLE guide_book (id INT NOT NULL, parent_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, enable BOOLEAN DEFAULT false NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D203985D727ACA70 ON guide_book (parent_id)');
        $this->addSql('CREATE TABLE guide_book_translation (id INT NOT NULL, translatable_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, locale VARCHAR(5) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FA126EDE2C2AC5D3 ON guide_book_translation (translatable_id)');
        $this->addSql('CREATE UNIQUE INDEX guide_book_translation_unique_translation ON guide_book_translation (translatable_id, locale)');
        $this->addSql('CREATE TABLE installer_email (id INT NOT NULL, email VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, state_short VARCHAR(255) DEFAULT NULL, zip_code_min INT DEFAULT NULL, zip_code_max INT DEFAULT NULL, call_back_url VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE installer_quota_submission_id (id INT NOT NULL, installer_email_id INT DEFAULT NULL, submission_id VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F3806B442B9BDBE7 ON installer_quota_submission_id (installer_email_id)');
        $this->addSql('CREATE TABLE native_strategy (id INT NOT NULL, form_id INT DEFAULT NULL, type_id INT DEFAULT NULL, next_type_id INT DEFAULT NULL, table_form_id INT DEFAULT NULL, assign_for_process_starter BOOLEAN DEFAULT NULL, never_complete BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B2C33025FF69B7D ON native_strategy (form_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B2C3302C54C8C93 ON native_strategy (type_id)');
        $this->addSql('CREATE INDEX IDX_5B2C33027C2A631 ON native_strategy (next_type_id)');
        $this->addSql('CREATE INDEX IDX_5B2C33025DC5DA72 ON native_strategy (table_form_id)');
        $this->addSql('CREATE TABLE notification (id INT NOT NULL, user_identity VARCHAR(255) NOT NULL, message VARCHAR(255) DEFAULT NULL, viewed BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE oauth_state (id INT NOT NULL, site_redirect_id INT DEFAULT NULL, state VARCHAR(255) NOT NULL, user_state VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_249038EA5F03B8FD ON oauth_state (site_redirect_id)');
        $this->addSql('CREATE TABLE organization (id INT NOT NULL, parent_id INT DEFAULT NULL, user_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, edrpou VARCHAR(255) NOT NULL, "default" BOOLEAN NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1EE637C2B36786B ON organization (title)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1EE637CD2841C5B ON organization (edrpou)');
        $this->addSql('CREATE INDEX IDX_C1EE637C727ACA70 ON organization (parent_id)');
        $this->addSql('CREATE INDEX IDX_C1EE637CA76ED395 ON organization (user_id)');
        $this->addSql('CREATE TABLE organization_join_flow (id INT NOT NULL, user_id INT DEFAULT NULL, data_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FBAF41EFA76ED395 ON organization_join_flow (user_id)');
        $this->addSql('CREATE INDEX IDX_FBAF41EF37F5A13C ON organization_join_flow (data_id)');
        $this->addSql('CREATE TABLE organization_join_flow_data (id INT NOT NULL, edrpou VARCHAR(255) NOT NULL, role VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE organization_join_invite (id INT NOT NULL, user_id INT DEFAULT NULL, organization_id INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, oauth_user_state VARCHAR(255) NOT NULL, drfo_code VARCHAR(255) NOT NULL, invite_url VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, job_title VARCHAR(255) DEFAULT NULL, full_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5F50298AA76ED395 ON organization_join_invite (user_id)');
        $this->addSql('CREATE INDEX IDX_5F50298A32C8A3DE ON organization_join_invite (organization_id)');
        $this->addSql('CREATE TABLE organization_join_task (id INT NOT NULL, flow_id INT DEFAULT NULL, data_id INT DEFAULT NULL, user_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FB114CBA7EB60D1B ON organization_join_task (flow_id)');
        $this->addSql('CREATE INDEX IDX_FB114CBA37F5A13C ON organization_join_task (data_id)');
        $this->addSql('CREATE INDEX IDX_FB114CBAA76ED395 ON organization_join_task (user_id)');
        $this->addSql('CREATE TABLE organization_user_role (id INT NOT NULL, organization_id INT DEFAULT NULL, user_id INT DEFAULT NULL, role VARCHAR(255) NOT NULL, "default" BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_15DF1CA532C8A3DE ON organization_user_role (organization_id)');
        $this->addSql('CREATE INDEX IDX_15DF1CA5A76ED395 ON organization_user_role (user_id)');
        $this->addSql('CREATE TABLE refresh_token (id INT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74F2195C74F2195 ON refresh_token (refresh_token)');
        $this->addSql('CREATE TABLE site_redirect (id INT NOT NULL, redirect_url VARCHAR(255) NOT NULL, auth_success_redirect_url VARCHAR(255) DEFAULT NULL, alias VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF4121F1E16C6B94 ON site_redirect (alias)');
        $this->addSql('CREATE TABLE sync_user_from_keycloak (id SERIAL NOT NULL, user_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F2DE5AFFA76ED395 ON sync_user_from_keycloak (user_id)');
        $this->addSql('CREATE TABLE "user" (id SERIAL NOT NULL, uuid UUID NOT NULL, email VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, middle_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, edrpou_code VARCHAR(255) DEFAULT NULL, drfo_code VARCHAR(255) DEFAULT NULL, gender VARCHAR(255) DEFAULT NULL, code VARCHAR(255) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, password_updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, account_type VARCHAR(255) DEFAULT NULL, reset_password_hash VARCHAR(255) DEFAULT NULL, is_verified_email BOOLEAN DEFAULT false NOT NULL, is_company BOOLEAN DEFAULT false NOT NULL, has_password BOOLEAN DEFAULT false NOT NULL, token VARCHAR(255) DEFAULT NULL, confirm_email_hash VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6492A0E42BF ON "user" (edrpou_code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F4252125 ON "user" (drfo_code)');
        $this->addSql('CREATE TABLE user_jwt_token (id SERIAL NOT NULL, user_id INT DEFAULT NULL, jwt_token TEXT DEFAULT NULL, refresh_token TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F5DB12C5A76ED395 ON user_jwt_token (user_id)');
        $this->addSql('ALTER TABLE application_process ADD CONSTRAINT FK_6DA31DA5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_process ADD CONSTRAINT FK_6DA31DA5C54C8C93 FOREIGN KEY (type_id) REFERENCES application_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_task ADD CONSTRAINT FK_A592B3AD5FF69B7D FOREIGN KEY (form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_task ADD CONSTRAINT FK_A592B3ADC54C8C93 FOREIGN KEY (type_id) REFERENCES application_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_task ADD CONSTRAINT FK_A592B3ADFFFE75C0 FOREIGN KEY (parent_task_id) REFERENCES application_task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camunda_strategy ADD CONSTRAINT FK_58CFFD0FAD73CA38 FOREIGN KEY (default_form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camunda_strategy ADD CONSTRAINT FK_58CFFD0FC54C8C93 FOREIGN KEY (type_id) REFERENCES application_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE camunda_strategy ADD CONSTRAINT FK_58CFFD0F5DC5DA72 FOREIGN KEY (table_form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE application_flow.camunda_task_filter ADD CONSTRAINT FK_A3D6132CC7D4C284 FOREIGN KEY (camunda_strategy_id) REFERENCES camunda_strategy (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_io ADD CONSTRAINT FK_C82442F5C24EAF86 FOREIGN KEY (started_process_type_id) REFERENCES application_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_io_process_resource ADD CONSTRAINT FK_93C3B8752DBEEF3B FOREIGN KEY (parent_form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_io_process_resource ADD CONSTRAINT FK_93C3B87589329D25 FOREIGN KEY (resource_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_process_submission ADD CONSTRAINT FK_5CD290805FF69B7D FOREIGN KEY (form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_task_submission ADD CONSTRAINT FK_77704C855FF69B7D FOREIGN KEY (form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guide_book ADD CONSTRAINT FK_D203985D727ACA70 FOREIGN KEY (parent_id) REFERENCES guide_book (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE guide_book_translation ADD CONSTRAINT FK_FA126EDE2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES guide_book (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE installer_quota_submission_id ADD CONSTRAINT FK_F3806B442B9BDBE7 FOREIGN KEY (installer_email_id) REFERENCES installer_email (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE native_strategy ADD CONSTRAINT FK_5B2C33025FF69B7D FOREIGN KEY (form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE native_strategy ADD CONSTRAINT FK_5B2C3302C54C8C93 FOREIGN KEY (type_id) REFERENCES application_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE native_strategy ADD CONSTRAINT FK_5B2C33027C2A631 FOREIGN KEY (next_type_id) REFERENCES application_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE native_strategy ADD CONSTRAINT FK_5B2C33025DC5DA72 FOREIGN KEY (table_form_id) REFERENCES form_io (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE oauth_state ADD CONSTRAINT FK_249038EA5F03B8FD FOREIGN KEY (site_redirect_id) REFERENCES site_redirect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637C727ACA70 FOREIGN KEY (parent_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_flow ADD CONSTRAINT FK_FBAF41EFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_flow ADD CONSTRAINT FK_FBAF41EF37F5A13C FOREIGN KEY (data_id) REFERENCES organization_join_flow_data (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_invite ADD CONSTRAINT FK_5F50298AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_invite ADD CONSTRAINT FK_5F50298A32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_task ADD CONSTRAINT FK_FB114CBA7EB60D1B FOREIGN KEY (flow_id) REFERENCES organization_join_flow (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_task ADD CONSTRAINT FK_FB114CBA37F5A13C FOREIGN KEY (data_id) REFERENCES organization_join_flow_data (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_join_task ADD CONSTRAINT FK_FB114CBAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_user_role ADD CONSTRAINT FK_15DF1CA532C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE organization_user_role ADD CONSTRAINT FK_15DF1CA5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sync_user_from_keycloak ADD CONSTRAINT FK_F2DE5AFFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_jwt_token ADD CONSTRAINT FK_F5DB12C5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE application_process_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE application_task_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE application_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE camunda_strategy_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE application_flow.camunda_task_filter_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE certificate_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE email_template_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE file_upload_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE form_io_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE form_io_process_resource_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE form_process_submission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE form_process_submission_variable_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE form_submission_edit_locker_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE form_task_submission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE guide_book_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE guide_book_translation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE installer_email_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE installer_quota_submission_id_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE native_strategy_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE oauth_state_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_join_flow_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_join_flow_data_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_join_invite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_join_task_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE organization_user_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refresh_tokens_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE site_redirect_id_seq CASCADE');
        $this->addSql('ALTER TABLE application_process DROP CONSTRAINT FK_6DA31DA5A76ED395');
        $this->addSql('ALTER TABLE application_process DROP CONSTRAINT FK_6DA31DA5C54C8C93');
        $this->addSql('ALTER TABLE application_task DROP CONSTRAINT FK_A592B3AD5FF69B7D');
        $this->addSql('ALTER TABLE application_task DROP CONSTRAINT FK_A592B3ADC54C8C93');
        $this->addSql('ALTER TABLE application_task DROP CONSTRAINT FK_A592B3ADFFFE75C0');
        $this->addSql('ALTER TABLE camunda_strategy DROP CONSTRAINT FK_58CFFD0FAD73CA38');
        $this->addSql('ALTER TABLE camunda_strategy DROP CONSTRAINT FK_58CFFD0FC54C8C93');
        $this->addSql('ALTER TABLE camunda_strategy DROP CONSTRAINT FK_58CFFD0F5DC5DA72');
        $this->addSql('ALTER TABLE application_flow.camunda_task_filter DROP CONSTRAINT FK_A3D6132CC7D4C284');
        $this->addSql('ALTER TABLE form_io DROP CONSTRAINT FK_C82442F5C24EAF86');
        $this->addSql('ALTER TABLE form_io_process_resource DROP CONSTRAINT FK_93C3B8752DBEEF3B');
        $this->addSql('ALTER TABLE form_io_process_resource DROP CONSTRAINT FK_93C3B87589329D25');
        $this->addSql('ALTER TABLE form_process_submission DROP CONSTRAINT FK_5CD290805FF69B7D');
        $this->addSql('ALTER TABLE form_task_submission DROP CONSTRAINT FK_77704C855FF69B7D');
        $this->addSql('ALTER TABLE guide_book DROP CONSTRAINT FK_D203985D727ACA70');
        $this->addSql('ALTER TABLE guide_book_translation DROP CONSTRAINT FK_FA126EDE2C2AC5D3');
        $this->addSql('ALTER TABLE installer_quota_submission_id DROP CONSTRAINT FK_F3806B442B9BDBE7');
        $this->addSql('ALTER TABLE native_strategy DROP CONSTRAINT FK_5B2C33025FF69B7D');
        $this->addSql('ALTER TABLE native_strategy DROP CONSTRAINT FK_5B2C3302C54C8C93');
        $this->addSql('ALTER TABLE native_strategy DROP CONSTRAINT FK_5B2C33027C2A631');
        $this->addSql('ALTER TABLE native_strategy DROP CONSTRAINT FK_5B2C33025DC5DA72');
        $this->addSql('ALTER TABLE oauth_state DROP CONSTRAINT FK_249038EA5F03B8FD');
        $this->addSql('ALTER TABLE organization DROP CONSTRAINT FK_C1EE637C727ACA70');
        $this->addSql('ALTER TABLE organization DROP CONSTRAINT FK_C1EE637CA76ED395');
        $this->addSql('ALTER TABLE organization_join_flow DROP CONSTRAINT FK_FBAF41EFA76ED395');
        $this->addSql('ALTER TABLE organization_join_flow DROP CONSTRAINT FK_FBAF41EF37F5A13C');
        $this->addSql('ALTER TABLE organization_join_invite DROP CONSTRAINT FK_5F50298AA76ED395');
        $this->addSql('ALTER TABLE organization_join_invite DROP CONSTRAINT FK_5F50298A32C8A3DE');
        $this->addSql('ALTER TABLE organization_join_task DROP CONSTRAINT FK_FB114CBA7EB60D1B');
        $this->addSql('ALTER TABLE organization_join_task DROP CONSTRAINT FK_FB114CBA37F5A13C');
        $this->addSql('ALTER TABLE organization_join_task DROP CONSTRAINT FK_FB114CBAA76ED395');
        $this->addSql('ALTER TABLE organization_user_role DROP CONSTRAINT FK_15DF1CA532C8A3DE');
        $this->addSql('ALTER TABLE organization_user_role DROP CONSTRAINT FK_15DF1CA5A76ED395');
        $this->addSql('ALTER TABLE sync_user_from_keycloak DROP CONSTRAINT FK_F2DE5AFFA76ED395');
        $this->addSql('ALTER TABLE user_jwt_token DROP CONSTRAINT FK_F5DB12C5A76ED395');
        $this->addSql('DROP TABLE application_process');
        $this->addSql('DROP TABLE application_task');
        $this->addSql('DROP TABLE application_type');
        $this->addSql('DROP TABLE camunda_strategy');
        $this->addSql('DROP TABLE application_flow.camunda_task_filter');
        $this->addSql('DROP TABLE certificate');
        $this->addSql('DROP TABLE email_template');
        $this->addSql('DROP TABLE file_upload');
        $this->addSql('DROP TABLE form_io');
        $this->addSql('DROP TABLE form_io_process_resource');
        $this->addSql('DROP TABLE form_process_submission');
        $this->addSql('DROP TABLE form_process_submission_variable');
        $this->addSql('DROP TABLE form_submission_edit_locker');
        $this->addSql('DROP TABLE form_task_submission');
        $this->addSql('DROP TABLE guide_book');
        $this->addSql('DROP TABLE guide_book_translation');
        $this->addSql('DROP TABLE installer_email');
        $this->addSql('DROP TABLE installer_quota_submission_id');
        $this->addSql('DROP TABLE native_strategy');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE oauth_state');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE organization_join_flow');
        $this->addSql('DROP TABLE organization_join_flow_data');
        $this->addSql('DROP TABLE organization_join_invite');
        $this->addSql('DROP TABLE organization_join_task');
        $this->addSql('DROP TABLE organization_user_role');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE site_redirect');
        $this->addSql('DROP TABLE sync_user_from_keycloak');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_jwt_token');
    }
}
